# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99b6cd0cfae285b0785887c29412709e399ab4511a709bac4401e8fbbb27ae1d2e6d40482eab75a51fe6dafe2de90ee08773bf45290995e0e4ac4b82ef9b7934

test:
  secret_key_base: 5dcb2afe9faea69e2470c3b8de59e7ccc1dd4c09648ef46d350a6b8ebedec81893da645f374ba2c457759e77d95d1d62e6bed11539432fe80902d47f2e9b309c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
